import 'package:flutter/foundation.dart';
import '../model/seed_model.dart';

class SeedRepository extends ChangeNotifier {
  final List<Seed> _seeds = const [
    Seed(
      id: '9',
      localName: 'Bell Pepper',
      englishName: 'Bell Pepper',
      scientificName: 'Capsicum annuum',
      category: 'Vegetables',
      subgroup: 'Fruit Vegetable / Pod',
      imagePlaceholder: 'assets/images/bellpepper.png',
      idealSoil: 'Fertile, well-draining loamy soil with a slightly acidic to neutral pH',
      growingSeason: 'Tag-init or warm dry months (Requires full sun and high warmth for optimal fruiting)',
      wateringFreq: 'Consistent and moderate watering; allow soil to dry slightly between waterings to prevent root rot',
      pestControl: 'Using row covers early on and monitoring for aphids, spider mites, and fruit borers',
      additionalInfo: 'Benefited by staking for support when heavy with fruit; changes color and sweetness as it ripens from green to red, yellow, or orange.',
      harvestDurationDays: 75,
    ),
    Seed(
      id: '6',
      localName: 'Baguio Beans',
      englishName: 'Green Beans',
      scientificName: 'Phaseolus vulgaris',
      category: 'Vegetables',
      subgroup: 'Legume / Pod Vegetable',
      imagePlaceholder: 'assets/images/green_beans.png',
      idealSoil: 'Loose, fertile, well-draining loamy soil with a neutral pH',
      growingSeason: 'Tag-init or cool dry months (Thrives in moderate temperatures)',
      wateringFreq: 'Regular watering at the base; keep soil evenly moist especially during flowering and pod development',
      pestControl: 'Crop rotation and manual removal of bean beetles or aphids',
      additionalInfo: 'Available in bush and pole varieties; pole types require stakes or trellis support.',
      harvestDurationDays: 60,
    ),
    Seed(
      id: '26',
      localName: 'Kabute',
      englishName: 'Button Mushroom',
      scientificName: 'Agaricus bisporus',
      category: 'Fungi',
      subgroup: 'Mushroom / Fleshy Fungi',
      imagePlaceholder: 'assets/images/button_mushroom.png',
      idealSoil: 'Nutrient-rich pasteurized compost or manure-based substrate mixed with peat moss or casing soil',
      growingSeason: 'Year-round indoor cultivation (Requires controlled cool, dark, and humid environments)',
      wateringFreq: 'Misting the casing layer consistently to maintain high humidity without making the substrate waterlogged',
      pestControl: 'Maintaining strict hygiene and using sterile casing layers to prevent sciarid flies and mold contamination',
      additionalInfo: 'Not a green plant; grows from spores or mycelium spawn in complete darkness before pinning and fruiting in cooler conditions.',
      harvestDurationDays: 60,
    ),
    Seed(
      id: '22',
      localName: 'Calamansi',
      englishName: 'Calamansi',
      scientificName: 'X Citrofortunella microcarpa',
      category: 'Fruits',
      subgroup: 'Citrus / Tree Fruit',
      imagePlaceholder: 'assets/images/calamansi.png',
      idealSoil: 'Rich, fertile, well-draining loamy soil with a slightly acidic pH',
      growingSeason: 'Year-round tropical growth (Fruiting peaks during warm months and after rains)',
      wateringFreq: 'Regular and consistent watering; keep soil moist but ensure proper drainage to prevent root rot',
      pestControl: 'Monitoring for citrus leaf miners, aphids, and scale insects; prune dead branches to maintain airflow',
      additionalInfo: 'Hardy and compact citrus tree widely used in Filipino cuisine; highly productive and can be grown easily in containers or backyards.',
      harvestDurationDays: 180,
    ),
    Seed(
      id: '11',
      localName: 'Karot',
      englishName: 'Carrot',
      scientificName: 'Daucus carota subsp. sativus',
      category: 'Vegetables',
      subgroup: 'Root Vegetable',
      imagePlaceholder: 'assets/images/Carrot.png',
      idealSoil: 'Loose, deep, sandy or fine loamy soil free of rocks to allow straight root growth',
      growingSeason: 'Tag-lamig or cool months (Prefers cooler temperatures for sweet and crisp roots)',
      wateringFreq: 'Consistent and even moisture; erratic watering can cause roots to split or become woody',
      pestControl: 'Thinning seedlings properly and using floating row covers to deter carrot rust flies',
      additionalInfo: 'Direct seeding is recommended as they do not transplant well; takes about 70-80 days to mature.',
      harvestDurationDays: 75,
    ),
    Seed(
      id: '8',
      localName: 'Cherry Kamatis',
      englishName: 'Cherry Tomato',
      scientificName: 'Solanum lycopersicum var. cerasiforme',
      category: 'Vegetables',
      subgroup: 'Fruit Vegetable',
      imagePlaceholder: 'assets/images/cherry_tomato.jpg',
      idealSoil: 'Rich, well-draining loamy soil with plenty of organic matter',
      growingSeason: 'Tag-init or dry transition (Thrives in abundant sunlight)',
      wateringFreq: 'Regular and consistent watering at the base; avoid erratic watering to prevent fruit splitting',
      pestControl: 'Good air circulation through pruning and organic insecticidal soap for aphids or whiteflies',
      additionalInfo: 'Produces abundant small, sweet fruits in clusters; heavily prolific and often easier to grow than standard tomatoes.',
      harvestDurationDays: 65,
    ),
    Seed(
      id: '17',
      localName: 'Siling Labuyo',
      englishName: 'Chili Pepper',
      scientificName: 'Capsicum frutescens',
      category: 'Vegetables',
      subgroup: 'Fruit Vegetable / Pod',
      imagePlaceholder: 'assets/images/chili.png',
      idealSoil: 'Fertile, loose, well-draining loamy soil with a slightly acidic to neutral pH',
      growingSeason: 'Tag-init or year-round tropical warmth (Thrives in high heat and intense sunlight)',
      wateringFreq: 'Moderate watering; allow the soil to dry out between waterings to encourage stronger root growth and hotter fruit',
      pestControl: 'Monitoring for aphids, whiteflies, and spider mites; easily managed with neem oil or insecticidal soap',
      additionalInfo: 'Perennial plant that can fruit continuously for years; compact and hardy, known for its fiery heat.',
      harvestDurationDays: 90,
    ),
    Seed(
      id: '5',
      localName: 'Pipino',
      englishName: 'Cucumber',
      scientificName: 'Cucumis sativus',
      category: 'Vegetables',
      subgroup: 'Vining Vegetable',
      imagePlaceholder: 'assets/images/cucumber.png',
      idealSoil: 'Rich, well-draining loamy soil with high organic matter',
      growingSeason: 'Tag-init or early Tag-ulan (Best grown in dry or warm months with consistent sun)',
      wateringFreq: 'Frequent and consistent watering; keep soil moist to prevent bitter fruit',
      pestControl: 'Netting or row covers to deter cucumber beetles and melon aphids',
      additionalInfo: 'Requires trellising or vertical space for vining varieties; fast-growing and harvests in about 50-70 days.',
      harvestDurationDays: 60,
    ),
    Seed(
      id: '1',
      localName: 'Talong',
      englishName: 'Eggplant',
      scientificName: 'Solanum melongena',
      category: 'Vegetables',
      subgroup: 'Nightshades',
      imagePlaceholder: 'assets/images/eggplant.png',
      idealSoil: 'Loamy soil mixed with vermicompost & CRH',
      growingSeason: 'Year-round (Best during Tag-init)',
      wateringFreq: 'Daily (Keep soil moist, avoid waterlogging)',
      pestControl: 'Neem oil or manual removal of fruit and shoot borers',
      additionalInfo: 'Requires full sun exposure and staking as branches heavy fruit.',
      harvestDurationDays: 75,
    ),
    Seed(
      id: '16',
      localName: 'Bawang',
      englishName: 'Garlic',
      scientificName: 'Allium sativum',
      category: 'Vegetables',
      subgroup: 'Bulb Vegetable',
      imagePlaceholder: 'assets/images/garlic.png',
      idealSoil: 'Rich, well-draining, loose loamy soil with a neutral to slightly acidic pH',
      growingSeason: 'Tag-lamig or cool dry months (Requires a cool period for proper bulb and clove development)',
      wateringFreq: 'Regular watering during the bulbing phase; keep soil moderately moist and stop watering 2-3 weeks before harvest',
      pestControl: 'Mulching to suppress weeds and monitoring for onion thrips or stem and bulb nematodes',
      additionalInfo: 'Planted from individual cloves rather than seeds; takes approximately 6-8 months to fully mature depending on the variety.',
      harvestDurationDays: 210,
    ),
    Seed(
      id: '10',
      localName: 'Lettuce',
      englishName: 'Lettuce',
      scientificName: 'Lactuca sativa',
      category: 'Vegetables',
      subgroup: 'Leafy Vegetable',
      imagePlaceholder: 'assets/images/lettuce.png',
      idealSoil: 'Loose, moisture-retentive, rich loamy soil with high organic matter',
      growingSeason: 'Tag-lamig or cooler months (Sensitive to intense heat which causes bolting)',
      wateringFreq: 'Frequent, shallow watering to keep the soil consistently moist for tender leaves',
      pestControl: 'Slugs and snails management using physical barriers or organic baits',
      additionalInfo: 'Shallow root system makes it ideal for containers or hydroponics; fast-maturing harvestable in 30-45 days.',
      harvestDurationDays: 40,
    ),
    Seed(
      id: '4',
      localName: 'Mangga',
      englishName: 'Mango',
      scientificName: 'Mangifera indica',
      category: 'Fruits',
      subgroup: 'Tree Fruit',
      imagePlaceholder: 'assets/images/mango.png',
      idealSoil: 'Deep, well-drained loamy or alluvial soil',
      growingSeason: 'Tag-init (Flowers during dry transition)',
      wateringFreq: 'Deep watering when young; drought tolerant once established',
      pestControl: 'Bagging young fruits to prevent fruit fly damage',
      additionalInfo: 'Requires considerable vertical space; takes years to mature from seed.',
      harvestDurationDays: 120,
    ),
    Seed(
      id: '20',
      localName: 'Malunggay',
      englishName: 'Moringa',
      scientificName: 'Moringa oleifera',
      category: 'Vegetables',
      subgroup: 'Leafy Vegetable / Tree',
      imagePlaceholder: 'assets/images/malunggay.png',
      idealSoil: 'Light, sandy, or well-draining loamy soil; highly tolerant of poor soil conditions',
      growingSeason: 'Year-round tropical growth (Thrives exceptionally well during Tag-init and dry conditions)',
      wateringFreq: 'Frequent watering when young until established; highly drought-tolerant and prone to root rot if overwatered',
      pestControl: 'Pruning regularly to encourage bushy leaf growth and monitoring for caterpillars or aphids',
      additionalInfo: 'Fast-growing, highly nutritious multipurpose tree whose leaves, pods, and flowers are all edible; easily propagated from cuttings.',
      harvestDurationDays: 60,
    ),
    Seed(
      id: '18',
      localName: 'Mulberry',
      englishName: 'Mulberry',
      scientificName: 'Morus alba',
      category: 'Fruits',
      subgroup: 'Tree Fruit / Berry',
      imagePlaceholder: 'assets/images/mulberry.png',
      idealSoil: 'Deep, fertile, well-draining loamy soil with a neutral pH',
      growingSeason: 'Year-round tropical growth / Tag-init (Fruiting is triggered after pruning or dry spells)',
      wateringFreq: 'Regular watering when young; highly drought-tolerant once fully established',
      pestControl: 'Pruning old branches and maintaining airflow to prevent fungal leaf spot or scale insects',
      additionalInfo: 'Fast-growing fruit tree that can tolerate heavy pruning; leaves serve as the primary food source for silkworms.',
      harvestDurationDays: 90,
    ),
    Seed(
      id: '23',
      localName: 'Okra',
      englishName: 'Okra',
      scientificName: 'Abelmoschus esculentus',
      category: 'Vegetables',
      subgroup: 'Pod Vegetable',
      imagePlaceholder: 'assets/images/okra.png',
      idealSoil: 'Rich, fertile, well-draining loamy soil with a neutral to slightly acidic pH',
      growingSeason: 'Tag-init or year-round tropical warmth (Thrives in high temperatures and full sun)',
      wateringFreq: 'Regular watering at the base; drought-tolerant once established, but consistent moisture improves pod quality',
      pestControl: 'Monitoring for aphids, stink bugs, and flea beetles; use neem oil or companion planting if necessary',
      additionalInfo: 'Fast-growing plant that produces edible seed pods; harvest frequently while pods are tender to encourage continuous production.',
      harvestDurationDays: 60,
    ),
    Seed(
      id: '24',
      localName: 'Papaya',
      englishName: 'Papaya',
      scientificName: 'Carica papaya',
      category: 'Fruits',
      subgroup: 'Tree Fruit / Melon-like',
      imagePlaceholder: 'assets/images/papaya.png',
      idealSoil: 'Rich, highly fertile, loose, and very well-draining loamy soil; highly sensitive to waterlogging',
      growingSeason: 'Year-round tropical growth (Requires abundant sunlight and warmth for optimal fruiting)',
      wateringFreq: 'Regular and consistent watering; avoid soggy soil conditions at all costs to prevent root rot and collar rot',
      pestControl: 'Monitoring for papaya mealybugs, aphids, and spider mites; ensure good drainage and weed control to deter fungal issues',
      additionalInfo: 'Fast-growing, short-lived tree that yields fruit directly from its trunk; best grown from seeds and bears fruit within its first year.',
      harvestDurationDays: 240,
    ),
    Seed(
      id: '3',
      localName: 'Oyster Kabute',
      englishName: 'Pearl Oyster Mushroom',
      scientificName: 'Pleurotus ostreatus',
      category: 'Fungi',
      subgroup: 'Saprophytic Fungi',
      imagePlaceholder: 'assets/images/oyster_mushroom.png',
      idealSoil: 'Pasteurized sawdust mixed with rice straw & lime',
      growingSeason: 'Tag-ulan (Requires high humidity & shade)',
      wateringFreq: 'Mist substrate bags 2-3 times daily',
      pestControl: 'Keep fruiting area clean to avoid mold and fungus gnats',
      additionalInfo: 'Grows in dark, humid incubation rooms before fruiting in indirect light.',
      harvestDurationDays: 30,
    ),
    Seed(
      id: '12',
      localName: 'Patatas',
      englishName: 'Potato',
      scientificName: 'Solanum tuberosum',
      category: 'Vegetables',
      subgroup: 'Tuber Vegetable',
      imagePlaceholder: 'assets/images/potato.png',
      idealSoil: 'Loose, well-draining, slightly acidic loamy soil',
      growingSeason: 'Tag-lamig or cool dry months (Prefers cooler temperatures for tuber development)',
      wateringFreq: 'Even and consistent moisture; water deeply especially during tuber formation, then taper off before harvest',
      pestControl: 'Hilling soil around the stems as they grow to prevent tubers from turning green, and monitoring for potato beetles',
      additionalInfo: 'Grown from seed potatoes rather than true seeds; requires hilling and stores well after harvesting.',
      harvestDurationDays: 100,
    ),
    Seed(
      id: '14',
      localName: 'Pulang Sibuyas',
      englishName: 'Red Onion',
      scientificName: 'Allium cepa var. cepa',
      category: 'Vegetables',
      subgroup: 'Bulb Vegetable',
      imagePlaceholder: 'assets/images/red_onion.png',
      idealSoil: 'Fertile, well-draining, loose loamy soil rich in organic matter with a near-neutral pH',
      growingSeason: 'Tag-lamig or cool dry season (Best grown during the cooler months for optimal bulb enlargement)',
      wateringFreq: 'Consistent watering while bulbs are forming; taper off water as harvest approaches to encourage skin tightening and curing',
      pestControl: 'Weed management and monitoring for onion thrips or downy mildew with appropriate organic sprays',
      additionalInfo: 'Known for its mild, sweet flavor profile often used raw in salads; takes roughly 90-110 days to mature.',
      harvestDurationDays: 100,
    ),
    Seed(
      id: '25',
      localName: 'Sibuyas Dahon / Spring Onion',
      englishName: 'Scallion',
      scientificName: 'Allium fistulosum',
      category: 'Vegetables',
      subgroup: 'Leafy / Allium Vegetable',
      imagePlaceholder: 'assets/images/spring_onions.png',
      idealSoil: 'Rich, loose, well-draining loamy soil high in organic matter',
      growingSeason: 'Year-round tropical growth / Tag-lamig (Adapts exceptionally well across all seasons)',
      wateringFreq: 'Regular and consistent moisture; keep the soil evenly damp without letting it become waterlogged',
      pestControl: 'Low susceptibility to pests, but monitor for onion thrips or fungal root issues during heavy rains',
      additionalInfo: 'Extremely easy to propagate from kitchen scraps (root bases); can be harvested repeatedly by clipping the green shoots as they grow.',
      harvestDurationDays: 60,
    ),
    Seed(
      id: '15',
      localName: 'Sibuyas Tagalog',
      englishName: 'Shallot',
      scientificName: 'Allium ascalonicum',
      category: 'Vegetables',
      subgroup: 'Bulb Vegetable',
      imagePlaceholder: 'assets/images/shallot_1.png',
      idealSoil: 'Fertile, well-draining, loose loamy soil with a neutral pH and minimal moisture retention issues',
      growingSeason: 'Tag-lamig or dry transition months (Thrives in cooler, dry weather for cluster formation)',
      wateringFreq: 'Moderate and consistent watering during growth; withhold water completely a couple of weeks before harvest to cure the bulbs',
      pestControl: 'Ensure good spacing to prevent fungal blights and watch out for onion thrips or armyworms',
      additionalInfo: 'Grows in clusters or multipliers from a single planted bulb; milder and sweeter than standard onions with a shorter maturity period of about 60-90 days.',
      harvestDurationDays: 75,
    ),
    Seed(
      id: '21',
      localName: 'Kamote',
      englishName: 'Sweet Potato',
      scientificName: 'Ipomoea batatas',
      category: 'Vegetables',
      subgroup: 'Tuber / Root Vegetable',
      imagePlaceholder: 'assets/images/kamote.png',
      idealSoil: 'Loose, well-draining sandy loam soil; avoids excessive nitrogen to prevent heavy vine growth over root production',
      growingSeason: 'Year-round tropical growth / Tag-init to Tag-ulan (Adapts well across seasons)',
      wateringFreq: 'Regular watering while establishing vines, then moderate watering; taper off before harvest to prevent tuber splitting',
      pestControl: 'Monitoring for sweet potato weevils and wireworms by maintaining clean beds and rotating crops',
      additionalInfo: 'Propagated primarily through stem cuttings (tendrils) rather than seeds; both the nutritious tubers and the tender shoot tips are edible.',
      harvestDurationDays: 120,
    ),
    Seed(
      id: '7',
      localName: 'Kamatis',
      englishName: 'Tomatoes',
      scientificName: 'Solanum lycopersicum',
      category: 'Vegetables',
      subgroup: 'Fruit Vegetable',
      imagePlaceholder: 'assets/images/tomato.png',
      idealSoil: 'Rich, well-draining loamy soil enriched with organic compost',
      growingSeason: 'Tag-init or dry transition (Best planted before heavy rains to avoid root rot)',
      wateringFreq: 'Consistent watering at the base; avoid overhead watering to prevent fungal diseases',
      pestControl: 'Pruning lower leaves and using companion planting or organic sprays against hornworms and fruit worms',
      additionalInfo: 'Requires staking or cages for structural support; indeterminate varieties keep growing and producing for months.',
      harvestDurationDays: 75,
    ),
    Seed(
      id: '19',
      localName: 'Kangkong',
      englishName: 'Water Spinach',
      scientificName: 'Ipomoea aquatica',
      category: 'Vegetables',
      subgroup: 'Leafy Vegetable / Aquatic',
      imagePlaceholder: 'assets/images/kangkong.png',
      idealSoil: 'Rich, muddy, or heavily organic soil with high moisture retention',
      growingSeason: 'Year-round, especially thriving during Tag-ulan (Rainy season)',
      wateringFreq: 'Very frequent or constant watering; can be grown in wet soil, saturated beds, or shallow water bodies',
      pestControl: 'Monitoring for leaf miners and common caterpillars; usually resilient due to fast growth',
      additionalInfo: 'Extremely fast-growing leafy green that can be harvested repeatedly through stem cuttings; highly prolific in tropical climates.',
      harvestDurationDays: 30,
    ),
    Seed(
      id: '13',
      localName: 'Sibuyas Basha / Puting Sibuyas',
      englishName: 'White Onion',
      scientificName: 'Allium cepa',
      category: 'Vegetables',
      subgroup: 'Bulb Vegetable',
      imagePlaceholder: 'assets/images/white_onion.png',
      idealSoil: 'Fertile, well-draining, loose loamy soil with a neutral pH and low sulfur if mild flavor is desired',
      growingSeason: 'Tag-lamig or cool dry season (Bulbing is triggered by specific day lengths and cool temperatures)',
      wateringFreq: 'Regular and consistent moisture during the growing stage; reduce watering significantly as bulbs mature to prevent rot',
      pestControl: 'Proper spacing for air circulation and monitoring for onion thrips using neem oil or insecticidal soap',
      additionalInfo: 'Has a sharper, more pungent flavor than yellow onions and a shorter storage shelf life; takes around 90-120 days from sets or seeds.',
      harvestDurationDays: 105,
    ),
    Seed(
      id: '2',
      localName: 'Sitaw',
      englishName: 'Yardlong Bean',
      scientificName: 'Vigna unguiculata subsp. sesquipedalis',
      category: 'Vegetables',
      subgroup: 'Legumes',
      imagePlaceholder: 'assets/images/sitaw.png',
      idealSoil: 'Well-draining sandy loam with organic compost',
      growingSeason: 'Year-round (Thrives in dry season)',
      wateringFreq: 'Moderate, 2-3 times a week',
      pestControl: 'Yellow sticky traps for aphids',
      additionalInfo: 'Climbing vine that requires a trellis or netting support structure.',
      harvestDurationDays: 60,
    ),
  ];

  List<Seed> get seeds => List.unmodifiable(_seeds);
}